// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "bo1_c_ger_zombie_head1";
	a[1] = "bo1_c_ger_zombie_head2";
	a[2] = "bo1_c_ger_zombie_head3";
	a[3] = "bo1_c_ger_zombie_head4";
	return a;
}
