// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "bo1_char_ger_honorgd_body1_g_larmoff_1";
	a[1] = "bo1_char_ger_honorgd_body1_g_larmoff_2";
	a[2] = "bo1_char_ger_honorgd_body1_g_rarmoff_1";
	a[3] = "bo1_char_ger_honorgd_body1_g_rarmoff_2";
	return a;
}
