// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "bo1_char_ger_honorgd_body1_g_legsoff_1";
	a[1] = "bo1_char_ger_honorgd_body1_g_llegoff_1";
	a[2] = "bo1_char_ger_honorgd_body1_g_llegoff_2";
	a[3] = "bo1_char_ger_honorgd_body1_g_rlegoff_1";
	a[4] = "bo1_char_ger_honorgd_body1_g_rlegoff_2";
	return a;
}
