// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "bo2_c_zom_tomb_crusader_body_g_rarm_1a";
	a[1] = "bo2_c_zom_tomb_crusader_body_g_rarm_1c";
	a[2] = "bo2_c_zom_tomb_crusader_body_g_rarm_2b";
	a[3] = "bo2_c_zom_tomb_crusader_body_g_rarm_2c";
	a[4] = "bo2_c_zom_tomb_crusader_body_g_rarm_zc";
	a[5] = "bo2_c_zom_tomb_crusader_body_g_larm_1a";
	a[6] = "bo2_c_zom_tomb_crusader_body_g_larm_1c";
	a[7] = "bo2_c_zom_tomb_crusader_body_g_larm_2b";
	a[8] = "bo2_c_zom_tomb_crusader_body_g_larm_2c";
	a[9] = "bo2_c_zom_tomb_crusader_body_g_larm_zc";
	return a;
}
