// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "bo2_c_zom_tomb_crusader_body_g_legsoff_1a";
	a[1] = "bo2_c_zom_tomb_crusader_body_g_legsoff_1c";
	a[2] = "bo2_c_zom_tomb_crusader_body_g_legsoff_2b";
	a[3] = "bo2_c_zom_tomb_crusader_body_g_legsoff_2c";
	a[4] = "bo2_c_zom_tomb_crusader_body_g_legsoff_zc";
	a[5] = "bo2_c_zom_tomb_crusader_body_g_rleg_1a";
	a[6] = "bo2_c_zom_tomb_crusader_body_g_rleg_1c";
	a[7] = "bo2_c_zom_tomb_crusader_body_g_rleg_2b";
	a[8] = "bo2_c_zom_tomb_crusader_body_g_rleg_2c";
	a[9] = "bo2_c_zom_tomb_crusader_body_g_rleg_zc";
	a[10] = "bo2_c_zom_tomb_crusader_body_g_lleg_1a";
	a[11] = "bo2_c_zom_tomb_crusader_body_g_lleg_1c";
	a[12] = "bo2_c_zom_tomb_crusader_body_g_lleg_2b";
	a[13] = "bo2_c_zom_tomb_crusader_body_g_lleg_2c";
	a[14] = "bo2_c_zom_tomb_crusader_body_g_lleg_zc";
	return a;
}
