// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "bo2_c_zom_tomb_crusader_body_1a";
	a[1] = "bo2_c_zom_tomb_crusader_body_1c";
	a[2] = "bo2_c_zom_tomb_crusader_body_2b";
	a[3] = "bo2_c_zom_tomb_crusader_body_2c";
	a[4] = "bo2_c_zom_tomb_crusader_body_zc";
	return a;
}
